const fs = require('node:fs');
const file = 'C:/Users/user/Documents/Codex/korea-trip-hub/data/share-ui.json';
const data = JSON.parse(fs.readFileSync(file, 'utf8'));
const keys = ['heading','more','openApp','copyPaste','openHint','chatHint','appCopied','appManual','messageLabel','qr','qrHint','saveQr'];
const additions = {
  en: ['Share with friends or save for yourself','Choose a messaging or social app','Open sharing screen','Copy for chat','Choose a recipient, including yourself, and send in the app. Opening a draft does not send it.','Use Share to apps to choose an installed app, or copy the message and paste it into a chat.','Message copied. Open {app}, choose a chat, and paste it.','Select and copy the message below, then paste it into a {app} chat.','Message for {app}','Show QR code','Scan this QR code with WeChat or your phone camera to open the link. You can also save the QR image and share it in a chat.','Save QR image'],
  ko: ['친구에게 공유 · 나에게 저장','메신저·SNS 선택','공유창 열기','채팅에 붙여넣기','받는 사람(본인도 가능)을 선택한 후 앱에서 보내세요. 작성창을 여는 것만으로 전송되지는 않습니다.','앱으로 공유에서 설치된 앱을 선택하거나, 메시지를 복사해 채팅창에 붙여 넣으세요.','메시지를 복사했습니다. {app}을 열고 원하는 채팅창에 붙여 넣으세요.','아래 메시지를 선택해 복사한 뒤 {app} 채팅창에 붙여 넣으세요.','{app}에 보낼 메시지','QR 코드 보기','WeChat이나 휴대폰 카메라로 QR 코드를 스캔해 링크를 여세요. QR 이미지를 저장해 채팅으로 보낼 수도 있습니다.','QR 이미지 저장'],
  vi: ['Chia sẻ với bạn bè hoặc lưu cho mình','Chọn ứng dụng nhắn tin hoặc mạng xã hội','Mở màn hình chia sẻ','Sao chép để dán vào chat','Chọn người nhận, có thể là chính bạn, rồi gửi trong ứng dụng. Mở bản nháp chưa có nghĩa là đã gửi.','Dùng Chia sẻ qua ứng dụng để chọn ứng dụng đã cài, hoặc sao chép tin nhắn và dán vào cuộc trò chuyện.','Đã sao chép tin nhắn. Mở {app}, chọn cuộc trò chuyện rồi dán.','Chọn và sao chép tin nhắn bên dưới, rồi dán vào cuộc trò chuyện trên {app}.','Tin nhắn cho {app}','Hiện mã QR','Quét mã QR bằng WeChat hoặc camera điện thoại để mở liên kết. Bạn cũng có thể lưu ảnh QR và gửi trong cuộc trò chuyện.','Lưu ảnh QR'],
  th: ['แชร์ให้เพื่อนหรือเก็บไว้ให้ตัวเอง','เลือกแอปแชตหรือโซเชียล','เปิดหน้าจอแชร์','คัดลอกไปวางในแชต','เลือกผู้รับ รวมถึงตัวคุณเอง แล้วส่งในแอป การเปิดฉบับร่างยังไม่ได้ส่งข้อความ','ใช้แชร์ผ่านแอปเพื่อเลือกแอปที่ติดตั้ง หรือคัดลอกข้อความแล้ววางในแชต','คัดลอกข้อความแล้ว เปิด {app} เลือกแชตแล้ววางข้อความ','เลือกและคัดลอกข้อความด้านล่าง แล้ววางในแชตของ {app}','ข้อความสำหรับ {app}','แสดงรหัส QR','สแกนรหัส QR ด้วย WeChat หรือกล้องโทรศัพท์เพื่อเปิดลิงก์ หรือบันทึกภาพ QR แล้วส่งในแชต','บันทึกภาพ QR'],
  id: ['Bagikan ke teman atau simpan untuk diri sendiri','Pilih aplikasi pesan atau media sosial','Buka layar berbagi','Salin untuk chat','Pilih penerima, termasuk diri sendiri, lalu kirim di aplikasi. Membuka draf belum mengirim pesan.','Gunakan Bagikan ke aplikasi untuk memilih aplikasi terpasang, atau salin pesan dan tempelkan ke chat.','Pesan disalin. Buka {app}, pilih chat, lalu tempelkan.','Pilih dan salin pesan di bawah, lalu tempelkan ke chat {app}.','Pesan untuk {app}','Tampilkan kode QR','Pindai kode QR dengan WeChat atau kamera ponsel untuk membuka tautan. Kamu juga dapat menyimpan gambar QR dan membagikannya ke chat.','Simpan gambar QR'],
  ms: ['Kongsi dengan rakan atau simpan untuk diri sendiri','Pilih aplikasi mesej atau media sosial','Buka skrin perkongsian','Salin untuk sembang','Pilih penerima, termasuk diri sendiri, kemudian hantar dalam aplikasi. Membuka draf tidak menghantar mesej.','Gunakan Kongsi ke aplikasi untuk memilih aplikasi yang dipasang, atau salin mesej dan tampalkannya dalam sembang.','Mesej disalin. Buka {app}, pilih sembang dan tampalkan.','Pilih dan salin mesej di bawah, kemudian tampalkan dalam sembang {app}.','Mesej untuk {app}','Paparkan kod QR','Imbas kod QR dengan WeChat atau kamera telefon untuk membuka pautan. Anda juga boleh menyimpan imej QR dan berkongsi dalam sembang.','Simpan imej QR'],
  ja: ['友達に共有・自分用に保存','メッセージ・SNSアプリを選ぶ','共有画面を開く','チャット用にコピー','自分を含む送信先を選び、アプリで送信してください。下書きを開くだけでは送信されません。','アプリで共有からインストール済みのアプリを選ぶか、メッセージをコピーしてチャットに貼り付けてください。','メッセージをコピーしました。{app}を開き、送信先のチャットに貼り付けてください。','下のメッセージを選択してコピーし、{app}のチャットに貼り付けてください。','{app}に送るメッセージ','QRコードを表示','WeChatまたはスマートフォンのカメラでQRコードを読み取るとリンクを開けます。QR画像を保存してチャットで共有することもできます。','QR画像を保存'],
  zh: ['分享给朋友或保存给自己','选择聊天或社交应用','打开分享窗口','复制到聊天','选择接收人（也可以是自己），然后在应用中发送。打开草稿不会自动发送。','通过应用分享选择已安装的应用，或复制消息并粘贴到聊天窗口。','消息已复制。打开{app}，选择聊天并粘贴。','选择并复制下方消息，再粘贴到{app}聊天窗口。','发送到{app}的消息','显示二维码','用WeChat或手机相机扫描二维码打开链接。也可以保存二维码图片并发送到聊天中。','保存二维码图片'],
  'zh-TW': ['分享給朋友或儲存給自己','選擇聊天或社群應用程式','開啟分享視窗','複製到聊天','選擇收件人（也可以是自己），再於應用程式中傳送。開啟草稿不會自動傳送。','透過應用程式分享選擇已安裝的應用程式，或複製訊息並貼到聊天視窗。','已複製訊息。開啟{app}，選擇聊天並貼上。','選取並複製下方訊息，再貼到{app}聊天視窗。','傳送到{app}的訊息','顯示QR碼','用WeChat或手機相機掃描QR碼開啟連結。也可以儲存QR碼圖片並傳送到聊天中。','儲存QR碼圖片'],
  es: ['Comparte con amigos o guarda para ti','Elige una aplicación de mensajería o red social','Abrir pantalla para compartir','Copiar para el chat','Elige un destinatario, incluido tú mismo, y envía desde la aplicación. Abrir un borrador no lo envía.','Usa Compartir en aplicaciones para elegir una aplicación instalada, o copia el mensaje y pégalo en un chat.','Mensaje copiado. Abre {app}, elige un chat y pégalo.','Selecciona y copia el mensaje de abajo y pégalo en un chat de {app}.','Mensaje para {app}','Mostrar código QR','Escanea este QR con WeChat o la cámara del teléfono para abrir el enlace. También puedes guardar la imagen QR y compartirla en un chat.','Guardar imagen QR'],
  fr: ['Partager avec des amis ou garder pour soi','Choisir une messagerie ou un réseau social','Ouvrir le partage','Copier pour une discussion','Choisissez un destinataire, vous-même si vous le souhaitez, puis envoyez dans l’application. Ouvrir un brouillon ne l’envoie pas.','Utilisez Partager via une application pour choisir une application installée, ou copiez le message dans une discussion.','Message copié. Ouvrez {app}, choisissez une discussion et collez-le.','Sélectionnez et copiez le message ci-dessous, puis collez-le dans une discussion sur {app}.','Message pour {app}','Afficher le code QR','Scannez ce QR avec WeChat ou l’appareil photo du téléphone pour ouvrir le lien. Vous pouvez aussi enregistrer l’image QR et la partager dans une discussion.','Enregistrer l’image QR'],
  ru: ['Поделиться с друзьями или сохранить для себя','Выберите мессенджер или соцсеть','Открыть окно отправки','Скопировать для чата','Выберите получателя, в том числе себя, и отправьте в приложении. Открытие черновика не отправляет сообщение.','Выберите установленное приложение через «Поделиться через приложение» или скопируйте сообщение и вставьте его в чат.','Сообщение скопировано. Откройте {app}, выберите чат и вставьте его.','Выделите и скопируйте сообщение ниже, затем вставьте в чат {app}.','Сообщение для {app}','Показать QR-код','Отсканируйте QR-код в WeChat или камерой телефона, чтобы открыть ссылку. Можно также сохранить изображение QR и отправить его в чат.','Сохранить изображение QR']
};
for (const [locale, values] of Object.entries(additions)) {
  if(values.length !== keys.length) throw new Error(locale);
  Object.assign(data[locale], Object.fromEntries(keys.map((key, i) => [key, values[i]])));
}
fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n');
