import json
from pathlib import Path
root=Path(r'C:\Users\user\Documents\Codex\korea-trip-hub')
def update(path, fn):
 p=root/path; s=p.read_text(encoding='utf-8'); p.write_text(fn(s),encoding='utf-8')
update('components/TripPlanner.jsx',lambda s:s.replace('normalizeTrip, encodeTrip, decodeTrip','normalizeTrip, decodeTrip'))
update('components/SavedPlaces.jsx',lambda s:s.replace("import {track} from '../lib/analytics';","import ShareTools from './ShareTools';\nimport {tripShareUrl} from '../lib/share.mjs';").replace(",[url,setUrl]=useState('')",'').replace("setIds(next);setUrl('');if(!shared)save(next)","setIds(next);if(!shared)save(next);else {const u=new URL(location.href);u.searchParams.set('places',next.join(','));history.replaceState(null,'',u.href);}").replace(s[s.index(' async function share()'):s.index(' return <section')]," function shareUrl(){return tripShareUrl({origin:location.origin,locale,places:ids})}\n").replace('<button className="btn ghost" onClick={share}>{t.copy}</button>','').replace('</div></> }','</div><ShareTools locale={locale} title={t.savedPlaces} getUrl={shareUrl} selection /></> }').replace('{url&&<input className="trip-copy" aria-label={t.copy} value={url} readOnly onFocus={e=>e.target.select()}/>}',''))
update('app/[locale]/plan/[slug]/page.jsx',lambda s:s.replace('import ArticleTrust', 'import BudgetCalculator from "../../../../components/BudgetCalculator";\nimport ArticleTrust',1).replace('      <ArticleTrust locale=', '      {slug === "money" && <BudgetCalculator locale={locale} />}\n      <ArticleTrust locale='))
update('app/[locale]/guides/[slug]/page.jsx',lambda s:s.replace('import ArticleTrust','import BudgetCalculator from "../../../../components/BudgetCalculator";\nimport ArticleTrust',1).replace('      <ArticleTrust reviewed=', '      {slug.startsWith("korea-from-") && <BudgetCalculator locale={locale} />}\n      <ArticleTrust reviewed='))
update('components/NextSteps.jsx',lambda s:s.replace('href: L("plan/money")','href: L("plan/money") + "#budget"'))
update('app/[locale]/layout.jsx',lambda s:s.replace(s[s.index('        {/* AdSense loader'):s.index('        <Script\n          id="adsense"')], '        {/* Auto ads placements and formats are controlled in the AdSense account. */}\n'))

# Reuse translated general preparation paragraphs; keep identical structure in every locale.
# Add market-specific editorial budgeting advice without making price or visa claims.
market={
'en':['Korea trip from Indonesia: budget and itinerary','Prepare your Korea trip from Indonesia: check entry guidance, compare your budget in IDR, plan meals and save an itinerary to share.','Start with the entry guide for your passport, then compare the full trip cost in IDR. Choose places around your accommodation and send your route to your companions.','Compare your budget in IDR','Keep the original KRW quotes for accommodation, transport and activities. Use your own bank or payment-provider rate to compare the total in IDR, including payment fees. Enter the whole-trip quotes in the calculator below.','Plan meals around your needs','If you need halal food, check each restaurant’s current certification and ingredients directly. Do not infer suitability from a dish name. Save confirmed options near your chosen stops.','Compare your budget in VND','Keep the original KRW quotes for accommodation, transport and activities. Convert the whole-trip total into VND using a rate you have checked with your bank or payment provider, allowing for fees. Use the calculator below before comparing options.'],
'id':['Liburan ke Korea dari Indonesia: biaya dan itinerary','Siapkan liburan ke Korea dari Indonesia: cek panduan masuk, hitung anggaran dalam IDR, rencanakan makanan, lalu simpan dan bagikan itinerary.','Mulai dari panduan masuk sesuai paspormu, lalu bandingkan total biaya dalam IDR. Pilih tempat di sekitar penginapan dan kirim rutenya kepada teman perjalanan.','Bandingkan anggaran dalam IDR','Simpan penawaran asli dalam KRW untuk penginapan, transportasi, dan aktivitas. Gunakan kurs bank atau penyedia pembayaranmu untuk membandingkan total dalam IDR, termasuk biaya transaksi. Masukkan penawaran seluruh perjalanan ke kalkulator di bawah.','Rencanakan makanan sesuai kebutuhan','Jika membutuhkan makanan halal, periksa sertifikasi terkini dan bahan makanan langsung dengan restoran. Jangan menyimpulkan kesesuaian dari nama hidangan. Simpan pilihan yang sudah dikonfirmasi di dekat tempat tujuanmu.','Bandingkan anggaran dalam VND','Simpan penawaran asli dalam KRW untuk penginapan, transportasi, dan aktivitas. Konversikan total seluruh perjalanan ke VND dengan kurs yang sudah dicek di bank atau penyedia pembayaran, termasuk biaya transaksi. Gunakan kalkulator di bawah sebelum membandingkan pilihan.'],
'vi':['Du lịch Hàn Quốc từ Indonesia: ngân sách và lịch trình','Chuẩn bị đi Hàn Quốc từ Indonesia: xem hướng dẫn nhập cảnh, tính ngân sách bằng IDR, lên kế hoạch ăn uống, lưu và chia sẻ lịch trình.','Bắt đầu với hướng dẫn nhập cảnh theo hộ chiếu, rồi so sánh tổng chi phí bằng IDR. Chọn địa điểm quanh nơi lưu trú và gửi lịch trình cho bạn đồng hành.','So sánh ngân sách bằng IDR','Giữ báo giá gốc bằng KRW cho lưu trú, đi lại và hoạt động. Dùng tỷ giá của ngân hàng hoặc đơn vị thanh toán để so sánh tổng tiền bằng IDR, gồm cả phí giao dịch. Nhập báo giá cho cả chuyến đi vào công cụ bên dưới.','Lên kế hoạch ăn uống theo nhu cầu','Nếu cần đồ ăn halal, hãy kiểm tra chứng nhận hiện hành và thành phần trực tiếp với từng nhà hàng. Đừng suy đoán từ tên món ăn. Lưu các lựa chọn đã xác nhận gần điểm đến của bạn.','Tính ngân sách bằng VND','Giữ báo giá gốc bằng KRW cho lưu trú, đi lại và hoạt động. Đổi tổng chi phí cả chuyến đi sang VND theo tỷ giá đã kiểm tra với ngân hàng hoặc đơn vị thanh toán, tính cả phí. Dùng công cụ bên dưới để so sánh các phương án.'],
'ko':['인도네시아 출발 한국 여행: 예산과 일정','인도네시아에서 출발하는 한국 여행을 준비하세요. 입국 안내, IDR 예산 비교, 식사 계획과 일정 저장·공유를 한곳에서 확인하세요.','여권에 맞는 입국 안내부터 확인하고 전체 여행 비용을 IDR로 비교하세요. 숙소 주변의 방문지를 고르고 동행자에게 일정을 보내세요.','IDR로 예산 비교하기','숙박·교통·체험의 원래 KRW 견적을 보관하세요. 은행이나 결제사에서 확인한 환율로 수수료를 포함한 IDR 합계를 비교하세요. 아래 계산기에 전체 여행 견적을 입력할 수 있습니다.','식사 조건에 맞춰 계획하기','할랄 식사가 필요하다면 각 식당에 현재 인증과 재료를 직접 확인하세요. 음식 이름만으로 적합성을 판단하지 마세요. 방문지 근처에서 확인한 식당을 저장하세요.','VND로 예산 비교하기','숙박·교통·체험의 원래 KRW 견적을 보관하세요. 은행이나 결제사에서 확인한 환율로 전체 여행 합계를 VND로 환산하고 수수료도 고려하세요. 아래 계산기로 선택지를 비교하세요.'],
'ja':['インドネシア発の韓国旅行：予算と旅程','インドネシアからの韓国旅行を準備。入国案内、IDRでの予算比較、食事の計画、旅程の保存と共有をまとめました。','まずパスポートに合う入国案内を確認し、旅費全体をIDRで比較しましょう。宿泊先周辺の行き先を選び、仲間に旅程を送れます。','IDRで予算を比較','宿泊・交通・体験の元のKRW見積額を控えましょう。銀行や決済事業者で確認したレートを使い、手数料を含むIDR合計を比較します。下の計算機には旅行全体の見積額を入力してください。','食事の条件に合わせて計画','ハラール食が必要なら、各店に現在の認証と食材を直接確認しましょう。料理名だけで判断せず、訪問先の近くで確認できた店を保存してください。','VNDで予算を比較','宿泊・交通・体験の元のKRW見積額を控えましょう。銀行や決済事業者で確認したレートで旅行全体の合計をVNDに換算し、手数料も考慮します。下の計算機で選択肢を比較できます。'],
'zh':['从印度尼西亚去韩国：预算与行程','准备从印度尼西亚出发的韩国旅行：查看入境指南、比较IDR预算、安排餐饮，并保存和分享行程。','先查看与你的护照对应的入境指南，再用IDR比较整趟旅行费用。选择住宿附近的地点，并把路线发给旅伴。','用IDR比较预算','保留住宿、交通和活动的KRW原始报价。使用银行或支付机构的汇率，比较包含手续费的IDR总额。在下方计算器中输入整趟旅行的报价。','按饮食需求安排用餐','如需清真餐饮，请直接向每家餐厅核实当前认证和食材。不要仅凭菜名判断。保存目的地附近已确认的选择。','用VND比较预算','保留住宿、交通和活动的KRW原始报价。使用向银行或支付机构核实的汇率，将整趟旅行总额换算为VND，并考虑手续费。用下方计算器比较方案。'],
'zh-TW':['從印尼去韓國：預算與行程','準備從印尼出發的韓國旅行：查看入境指南、比較IDR預算、安排餐飲，並儲存及分享行程。','先查看與你的護照對應的入境指南，再用IDR比較整趟旅行費用。選擇住宿附近的地點，並將路線傳給旅伴。','用IDR比較預算','保留住宿、交通與活動的KRW原始報價。使用銀行或支付業者的匯率，比較包含手續費的IDR總額。在下方計算機輸入整趟旅行的報價。','依飲食需求安排用餐','若需清真餐飲，請直接向各餐廳確認目前的認證與食材。不要只憑菜名判斷。儲存目的地附近已確認的選擇。','用VND比較預算','保留住宿、交通與活動的KRW原始報價。使用向銀行或支付業者確認的匯率，將整趟旅行總額換算為VND，並考慮手續費。用下方計算機比較方案。'],
'th':['เที่ยวเกาหลีจากอินโดนีเซีย: งบประมาณและแผนเที่ยว','เตรียมเที่ยวเกาหลีจากอินโดนีเซีย: ดูข้อมูลเข้าเมือง เปรียบเทียบงบเป็น IDR วางแผนอาหาร บันทึกและแชร์แผนเที่ยว','เริ่มจากคู่มือเข้าเมืองตามหนังสือเดินทาง แล้วเปรียบเทียบค่าใช้จ่ายทั้งทริปเป็น IDR เลือกสถานที่ใกล้ที่พักและส่งเส้นทางให้เพื่อนร่วมทริป','เปรียบเทียบงบเป็น IDR','เก็บใบเสนอราคาที่พัก การเดินทาง และกิจกรรมใน KRW ใช้อัตราจากธนาคารหรือผู้ให้บริการชำระเงินเพื่อเปรียบเทียบยอดรวมเป็น IDR โดยรวมค่าธรรมเนียม กรอกราคาทั้งทริปในเครื่องคำนวณด้านล่าง','วางแผนอาหารตามความต้องการ','หากต้องการอาหารฮาลาล ให้ตรวจสอบใบรับรองปัจจุบันและส่วนผสมกับแต่ละร้านโดยตรง อย่าตัดสินจากชื่ออาหาร บันทึกร้านที่ยืนยันแล้วใกล้จุดหมายของคุณ','เปรียบเทียบงบเป็น VND','เก็บใบเสนอราคาที่พัก การเดินทาง และกิจกรรมใน KRW แปลงยอดรวมทั้งทริปเป็น VND โดยใช้อัตราที่ตรวจสอบกับธนาคารหรือผู้ให้บริการชำระเงินและเผื่อค่าธรรมเนียม ใช้เครื่องคำนวณด้านล่างเพื่อเปรียบเทียบตัวเลือก'],
'ms':['Ke Korea dari Indonesia: bajet dan jadual perjalanan','Sediakan perjalanan ke Korea dari Indonesia: semak panduan kemasukan, bandingkan bajet dalam IDR, rancang makanan, simpan dan kongsi jadual.','Mulakan dengan panduan kemasukan mengikut pasport, kemudian bandingkan jumlah kos dalam IDR. Pilih tempat berhampiran penginapan dan hantar laluan kepada rakan perjalanan.','Bandingkan bajet dalam IDR','Simpan sebut harga asal dalam KRW untuk penginapan, pengangkutan dan aktiviti. Gunakan kadar bank atau penyedia pembayaran untuk membandingkan jumlah dalam IDR, termasuk caj. Masukkan sebut harga seluruh perjalanan dalam kalkulator di bawah.','Rancang makanan mengikut keperluan','Jika memerlukan makanan halal, semak pensijilan semasa dan ramuan terus dengan setiap restoran. Jangan membuat andaian berdasarkan nama hidangan. Simpan pilihan yang disahkan berhampiran destinasi anda.','Bandingkan bajet dalam VND','Simpan sebut harga asal dalam KRW untuk penginapan, pengangkutan dan aktiviti. Tukar jumlah seluruh perjalanan kepada VND menggunakan kadar yang disemak dengan bank atau penyedia pembayaran, termasuk caj. Gunakan kalkulator di bawah untuk membandingkan pilihan.'],
'es':['Corea desde Indonesia: presupuesto e itinerario','Prepara tu viaje a Corea desde Indonesia: consulta la entrada, compara gastos en IDR, planifica las comidas y guarda y comparte tu itinerario.','Consulta primero la guía de entrada de tu pasaporte y compara el coste total en IDR. Elige lugares cerca de tu alojamiento y envía la ruta a tus compañeros.','Compara el presupuesto en IDR','Conserva los presupuestos originales en KRW de alojamiento, transporte y actividades. Usa el cambio de tu banco o proveedor de pagos para comparar el total en IDR, incluidas las comisiones. Introduce los importes de todo el viaje en la calculadora de abajo.','Planifica las comidas según tus necesidades','Si necesitas comida halal, consulta directamente con cada restaurante su certificación actual y los ingredientes. No lo deduzcas del nombre del plato. Guarda opciones confirmadas cerca de tus visitas.','Compara el presupuesto en VND','Conserva los presupuestos originales en KRW de alojamiento, transporte y actividades. Convierte el total del viaje a VND con un cambio verificado con tu banco o proveedor de pagos y cuenta las comisiones. Compara opciones con la calculadora de abajo.'],
'fr':['Corée depuis l’Indonésie : budget et itinéraire','Préparez votre voyage en Corée depuis l’Indonésie : formalités, budget en IDR, repas et itinéraire à enregistrer et partager.','Consultez le guide d’entrée correspondant à votre passeport, puis comparez le coût total en IDR. Choisissez des lieux proches de votre hébergement et envoyez le parcours à vos compagnons.','Comparez votre budget en IDR','Conservez les devis en KRW pour l’hébergement, les transports et les activités. Utilisez le taux de votre banque ou prestataire de paiement pour comparer le total en IDR, frais compris. Saisissez les devis de tout le séjour dans le calculateur ci-dessous.','Prévoyez les repas selon vos besoins','Si vous avez besoin de repas halal, vérifiez directement auprès de chaque restaurant sa certification actuelle et ses ingrédients. Ne vous fiez pas au nom du plat. Enregistrez les options confirmées près de vos étapes.','Comparez votre budget en VND','Conservez les devis en KRW pour l’hébergement, les transports et les activités. Convertissez le total du séjour en VND au taux vérifié auprès de votre banque ou prestataire de paiement, en tenant compte des frais. Comparez les options avec le calculateur ci-dessous.'],
'ru':['В Корею из Индонезии: бюджет и маршрут','Подготовьте поездку в Корею из Индонезии: условия въезда, бюджет в IDR, питание и маршрут, который можно сохранить и отправить друзьям.','Начните с правил въезда для вашего паспорта, затем сравните полную стоимость в IDR. Выберите места рядом с жильём и отправьте маршрут попутчикам.','Сравните бюджет в IDR','Сохраните исходные цены в KRW на жильё, транспорт и развлечения. Используйте курс банка или платёжного сервиса для сравнения общей суммы в IDR с учётом комиссий. Введите стоимость всей поездки в калькулятор ниже.','Планируйте питание по своим потребностям','Если вам нужна халяльная еда, уточните действующую сертификацию и состав блюд непосредственно в каждом ресторане. Не делайте выводов по названию блюда. Сохраните проверенные варианты рядом с вашими остановками.','Сравните бюджет в VND','Сохраните исходные цены в KRW на жильё, транспорт и развлечения. Переведите общую стоимость поездки в VND по проверенному курсу банка или платёжного сервиса с учётом комиссий. Сравните варианты с помощью калькулятора ниже.']}
for locale,text in market.items():
 path=root/('data/topics.json' if locale=='en' else f'data/topics.{locale}.json')
 data=json.loads(path.read_text(encoding='utf-8'))
 reference=data['items']['korea-from-vietnam']
 entry=json.loads(json.dumps(reference))
 entry.update(h1=text[0],metaTitle=text[0],metaDesc=text[1],answer=text[2],reviewed='2026-10-01')
 entry['sections'][0]['body']=[x.replace('/visa/vietnam/','/visa/indonesia/') for x in entry['sections'][0]['body']]
 entry['sections'][1]['h2']=text[3]
 entry['sections'][1]['body'][0]=text[4]
 entry['sections'][3]['h2']=text[5]
 entry['sections'][3]['body'][0]=text[6]
 data['items']['korea-from-indonesia']=entry
 reference['sections'][1]['h2']=text[7]
 reference['sections'][1]['body'][0]=text[8]
 reference['reviewed']='2026-10-01'
 if locale=='en':
  data['order'].append('korea-from-indonesia')
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Updated sharing integrations, budgeting and localized Indonesia/Vietnam guides.')
