const fs=require('fs'),path=require('path');
const root='C:/Users/user/Documents/Codex/korea-trip-hub';
const review=__dirname;
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const revisions={...read(path.join(review,'other-locales.json')),...read(path.join(review,'revisions.json'))};
const base=read(root+'/data/visa/vietnam.json'), overrides=read(root+'/data/visa/vietnam.i18n.json');
const urls=['https://www.visa.go.kr','https://overseas.mofa.go.kr/vn-vi/brd/m_2156/view.do?seq=760618','https://visaforkorea-vt.com/customercenter/notice/view/873','https://visaforkorea-hc.com/customercenter/notice/view/778','https://overseas.mofa.go.kr/vn-danang-vi/brd/m_22986/view.do?seq=47','https://visaforkorea-vt.com/info/service','https://visaforkorea-hc.com/info/service','https://www.e-arrivalcard.go.kr/portal/guide/navigator.do?locale=E','https://overseas.mofa.go.kr/est-en/brd/m_27860/view.do?seq=19','https://overseas.mofa.go.kr/in-mumbai-en/brd/m_1978/view.do?seq=759205'];
const brands=['Korea Visa Portal','C-3-9 · Vietnam','KVAC Hanoi','KVAC HCMC','Da Nang','KVAC Hanoi · USD / VND','KVAC HCMC · USD / VND','e-Arrival Card','Transit · B-2','Jeju'];
const ketaUrl='https://www.k-eta.go.kr/portal/guide/viewetaalification.do';
const mainValues={visa_type:'C-3-9 short-term tourist',max_stay:'Hanoi single-entry: 30 days; follow the issued visa',apply_at:'KVAC Hanoi / Ho Chi Minh City / Korean Consulate General in Da Nang'};
const passports={ja:'ハノイの案内では、有効期間が6か月を超えるパスポートの原本とコピーが必要です。',zh:'河内清单要求有效期超过6个月的护照原件和复印件。','zh-TW':'河內清單要求有效期超過6個月的護照正本及影本。',id:'Daftar Hanoi meminta paspor asli dan salinan dengan masa berlaku lebih dari 6 bulan.',ms:'Senarai Hanoi meminta pasport asal dan salinan yang sah lebih daripada 6 bulan.',th:'รายการฮานอยกำหนดหนังสือเดินทางฉบับจริงและสำเนาที่มีอายุเหลือมากกว่า 6 เดือน',es:'Hanói pide pasaporte original y copia, con más de 6 meses de validez.',fr:'Hanoï demande le passeport original et une copie, avec plus de 6 mois de validité.',ru:'Ханой требует оригинал и копию паспорта со сроком действия более 6 месяцев.'};
for(const loc of Object.keys(revisions)){
 const c=revisions[loc];
 if(loc==='en')c.processing=c.processing.replace(/ Hanoi lists[\s\S]*?respectively\./,'');
 if(loc==='vi')c.processing=c.processing.replace(/Hà Nội.*?9.*?6.*?12.*?7[^.]*\./,'');
 if(loc==='ko')c.processing=c.processing.replace(/하노이는.*?9.*?6.*?12.*?7[^.]*\./,'');
 const g=loc==='en'?base:{...structuredClone(base),...overrides[loc]};
 g.ui=g.ui||{official:'Official sources',source:'Source'};
 g.updated='2026-10-05';g.metaDesc=c.meta||`${g.verdict.headline} ${c.keta}`;
 g.verdict.sub=c.route;g.verdict.stay=c.stay;g.verdict.entry=g.verdict.type;
 g.entryNotice={factId:'visa-vietnam-keta',title:c.ketaTitle,body:c.keta,arrival:c.arrival,safety:c.safety,links:[{label:'K-ETA',url:ketaUrl},{label:'e-Arrival Card',url:urls[7]}]};
 g.highlights=[{icon:'🗓️',tone:'green',title:c.processingTitle,body:c.processing},{icon:'📁',tone:'blue',title:c.fundsTitle,body:c.docs}];
 g.tldr=[c.keta,c.route,c.docs,c.fee];
 g.jurisdiction.title=c.prepare||g.jurisdiction.title.replace(/Hanoi.*$/,'Hanoi · HCMC · Da Nang');
 g.jurisdiction.intro=c.route;g.jurisdiction.note=c.route;
 g.jurisdiction.zones=[{name:'KVAC Hanoi',covers:c.zones[0],centers:'Hanoi',site:'visaforkorea-vt.com',url:'https://visaforkorea-vt.com'},{name:'KVAC Ho Chi Minh City',covers:c.zones[1],centers:'Ho Chi Minh City',site:'visaforkorea-hc.com',url:'https://visaforkorea-hc.com'},{name:'Da Nang',covers:c.zones[2],centers:'Da Nang',site:'overseas.mofa.go.kr',url:urls[4]}];
 g.steps.items[2].title=c.prepare||g.documents.title;g.steps.items[2].detail=c.docs;
 g.steps.items[3].title=c.submit||g.jurisdiction.title;g.steps.items[3].detail=c.route;
 g.steps.items[4].detail=c.fee;g.steps.items[6].detail=c.collect;
 g.documents.intro=c.docs;
 g.documents.rows[0].how=c.passport||passports[loc];
 g.documents.rows[3].doc=c.fundsDoc;g.documents.rows[3].how=c.docs;
 g.documents.rows[5].doc=c.hotelDoc||'Hotel';g.documents.rows[5].how=c.hotel||c.docs;
 g.documents.rows[7].req='required';g.documents.rows[7].how=c.itinerary||c.docs;
 g.documents.rows.push({doc:c.idDoc||'CCCD / CMND',req:'required',where:'CCCD / CMND',how:c.idHow||c.route});
 g.funds.title=c.fundsTitle;g.funds.body=c.docs;g.funds.tips[0]=c.docs;
 g.pitfalls.items[0].d=c.wrongOffice||c.route;
 const answers=[c.keta,c.stay,c.route,c.docs,c.fee,c.group||c.docs,c.arrival,c.jeju,c.processing,g.faq.items[9].a];
 const ids=['keta','c39','jurisdiction','documents','fees','documents','arrival','jeju','processing','c39'];
 g.faq.items.forEach((it,i)=>{it.a=answers[i];it.factId='visa-vietnam-'+ids[i];});
 g.faq.items.push({q:c.ketaQ,a:c.keta,factId:'visa-vietnam-keta'},{q:c.transitQ,a:c.transit,factId:'visa-vietnam-transit'});
 const labels=c.officialLabels||brands.map(b=>`${g.ui.official||g.ui.source} · ${b}`);
 g.resources={title:g.ui.official||g.ui.source,intro:c.route,items:urls.map((url,i)=>({label:labels[i],src:new URL(url).hostname,url}))};
 g.official=urls.slice(0,5).map((url,i)=>({icon:i===0?'📄':'🏢',name:labels[i],url,what:i===0?g.steps.items[1].title:i===1?c.docs:i===4?c.zones[2]:c.zones[i-2]}));
 g.factValueLabels={[mainValues.visa_type]:g.verdict.type,[mainValues.max_stay]:c.stay,[mainValues.apply_at]:c.route};
 if(loc!=='en')overrides[loc]=g;
 const mp=root+'/messages/'+loc+'.json',m=read(mp);
 m.facts['visa-vietnam-c39']={claim:c.factClaim||`${c.keta} ${c.stay}`,notes:c.factNotes||c.route};save(mp,m);
}
save(root+'/data/visa/vietnam.json',base);save(root+'/data/visa/vietnam.i18n.json',overrides);
const fp=root+'/data/facts.json',facts=read(fp),f=facts.facts.find(f=>f.id==='visa-vietnam-c39');
Object.assign(f,{claim:revisions.en.factClaim,value:mainValues,source:'https://visaforkorea-vt.com/customercenter/notice/view/722',source_name:'KVAC Hanoi · C-3-9 checklist',verified:'2026-10-05',recheck_after:'2026-11-05',notes:revisions.en.factNotes});
const specs=[['keta',revisions.en.keta,ketaUrl,'K-ETA'],['processing',revisions.en.processing,urls[2],'KVAC Hanoi',[3]],['fees',revisions.en.fee,urls[5],'KVAC Hanoi',[6]],['jurisdiction',revisions.en.route,urls[4],'Korean Consulate General in Da Nang'],['documents',revisions.en.docs,f.source,'KVAC Hanoi'],['arrival',revisions.en.arrival,urls[7],'Korea Immigration Service'],['jeju',revisions.en.jeju,urls[9],'Embassy of Korea'],['transit',revisions.en.transit,urls[8],'Embassy of Korea']];
for(const [id,claim,source,source_name,extra=[]]of specs){facts.facts=facts.facts.filter(f=>f.id!=='visa-vietnam-'+id);facts.facts.push({id:'visa-vietnam-'+id,tier:'VOLATILE',status:'VERIFIED',claim,source,source_name,verified:'2026-10-05',recheck_after:'2026-11-05',notes:'Office-specific and conditional rules: confirm with the issuing authority before travel.',...(extra.length?{sources:extra.map(i=>({name:brands[i],url:urls[i]}))}:{})});}
facts.lastUpdated='2026-10-05';save(fp,facts);
console.log('Updated Vietnam guide in 12 languages and official fact records.');
